//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserShared
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserShared()
        {
            this.SharedComments = new HashSet<SharedComment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string SharedDetails { get; set; }
        public Nullable<System.DateTime> SharedTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SharedComment> SharedComments { get; set; }
        public virtual Userr Userr { get; set; }
    }
}
