//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFriend
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> FriendId { get; set; }
    
        public virtual Userr Userr { get; set; }
        public virtual Userr Userr1 { get; set; }
    }
}
